import {Chain} from "../chain"
import {Range} from "../util/range"
import {Store} from "./handlerContext"
import {SubstrateBlock, SubstrateEvent, SubstrateExtrinsic} from "./substrate"


export type EvmContractAddress = string
export type EvmTopic = string


/**
 * Encapsulates a Substrate Event generated by an EVM log.
 * 
 * This is a specific subtype of {@link SubstrateEvent}, where the name is always `evm.Log`
 * and it also contains additional EVM-specific information, such as 
 * {@link EvmContractAddress}, {@link EvmTopic}s, data and hash
 */
export interface EvmLogEvent extends SubstrateEvent {
    name: 'evm.Log'
    evmLogAddress: EvmContractAddress
    evmLogTopics: EvmTopic[]
    evmLogData: string
    evmHash: string
}

/**
 * 
 * Defines the context for the execution of an {@link EvmLogHandler} function, including a `store` ({@link Store}) 
 * instance to interact with the database, the `topcs`, `data` and `contractAddress` of the EVM log, as well as 
 * `txHash`, the transaction hash.
 * 
 * Also contains all Substrate infromation in the `substrate` field.
 * 
 * @see EventHandlerContext
 */
export interface EvmLogHandlerContext {
    topics: EvmTopic[]
    data: string
    txHash: string
    contractAddress: EvmContractAddress
    substrate: {
        _chain: Chain,
        event: SubstrateEvent,
        block: SubstrateBlock,
        extrinsic?: SubstrateExtrinsic
    }
    store: Store
}

/**
 * Defines signature for functions that should process Substrate EvmLogs
 */
export interface EvmLogHandler {
    (ctx: EvmLogHandlerContext): Promise<void>
}


export type EvmTopicSet = EvmTopic | null | undefined | EvmTopic[]

/**
 * Specifies an (optional) `range` ({@link Range}) of blocks and an (optional) array of {@link EvmTopicSet} via the 
 * `filter` field to limit {@link EvmLogHandler} function execution.
 */
export interface EvmLogHandlerOptions {
    range?: Range
    /**
     * EVM topic filter as defined by https://docs.ethers.io/v5/concepts/events/#events--filters
     */
    filter?: EvmTopicSet[]
}
