import {parse} from 'graphql'
import {getSchemaBuilder} from '../dialect'
import {buildModel, buildSchema} from '../model.schema'
import type {Model} from '../model'
import {EntityByIdQuery, EntityByPkQuery} from '../sql/query'

const MODEL: Model = buildModel(buildSchema(parse(`
    type Account @entity {
        id: ID!
        wallet: String!
    }

    type Transfer @entity(pk: ["id", "timestamp"]) {
        id: ID!
        timestamp: DateTime!
        amount: Int!
    }
`)))

const FIELDS = [{kind: 'scalar', field: 'id', aliases: ['id']}] as any


describe('EntityByPkQuery', function () {
    it('emits a single equality for a one-column key', function () {
        let q = new EntityByPkQuery(MODEL, 'postgres', 'Account', FIELDS, {id: '1'})
        expect(q.params).toEqual(['1'])
        expect(q.sql).toMatch(/where/i)
    })

    it('emits a conjunction for a composite key, in key order', function () {
        let ts = new Date('2020-01-01T00:00:00.000Z')
        let q = new EntityByPkQuery(MODEL, 'postgres', 'Transfer', FIELDS, {id: 't1', timestamp: ts})
        expect(q.params).toEqual(['t1', ts])
        expect(q.sql.toLowerCase()).toContain(' and ')
    })

    it('rejects an empty key', function () {
        expect(() => new EntityByPkQuery(MODEL, 'postgres', 'Account', FIELDS, {}))
            .toThrow(/at least one column/)
    })

    it('maps at most one row', function () {
        let q = new EntityByPkQuery(MODEL, 'postgres', 'Account', FIELDS, {id: '1'})
        expect(q.map([])).toBeUndefined()
        expect(() => q.map([['1'], ['2']])).toThrow()
    })

    // EntityByIdQuery is retained as a deprecated alias; nothing in the
    // dialects uses it any more, so it needs its own guard.
    it('is equivalent to the deprecated EntityByIdQuery for a one-column key', function () {
        let byPk = new EntityByPkQuery(MODEL, 'postgres', 'Account', FIELDS, {id: '1'})
        let byId = new EntityByIdQuery(MODEL, 'postgres', 'Account', FIELDS, '1')
        expect(byId.sql).toBe(byPk.sql)
        expect(byId.params).toEqual(byPk.params)
    })
})


describe('opencrud schema — pk query names', function () {
    async function fields(schema: string): Promise<string[]> {
        let model = buildModel(buildSchema(parse(schema)))
        let builder = await getSchemaBuilder({model})
        return Object.keys(builder.build().getQueryType()!.getFields())
    }

    it('installs both ById and ByPks for a single-column key', async function () {
        let names = await fields(`type Account @entity { id: ID! }`)
        expect(names).toContain('accountById')
        expect(names).toContain('accountByPks')
    })

    it('installs only ByPks for a composite key', async function () {
        let names = await fields(`
            type Transfer @entity(pk: ["id", "timestamp"]) {
                id: ID!
                timestamp: DateTime!
            }
        `)
        expect(names).toContain('transferByPks')
        expect(names).not.toContain('transferById')
    })

    it('rejects a queryName that collides with the generated ByPks query', async function () {
        // Without the guard this would silently overwrite one query with the
        // other, since both are written into the same field map.
        await expect(fields(`
            type Account @entity(queryName: "accountByPks") { id: ID! }
        `)).rejects.toThrow(/collides/)
    })
})
