version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
#    command: ["postgres", "-c", "log_statement=all"]

  gateway:
    image: subsquid/substrate-gateway:2.1.0
    depends_on:
      - db
    ports:
      - "${GW_PORT}:8000"
    command: [
      "--database-url", "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
    ]
