module.exports = class Initial1639752889411 {
  name = 'Initial1639752889411'

  async up(db) {
    await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "hex" text NOT NULL, "balance" numeric NOT NULL, "status" jsonb NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "from" bytea NOT NULL, "to" bytea NOT NULL, "value" numeric NOT NULL, "comment" text, "block" integer NOT NULL, "tip" numeric NOT NULL, "timestamp" numeric NOT NULL, "inserted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "extrinsic_id" text, "from_account_id" character varying, "to_account_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_e2f71240f767a903a4fe85ce25" ON "transfer" ("from_account_id") `)
    await db.query(`CREATE INDEX "IDX_e588c446185bd0c7e4861bb66b" ON "transfer" ("to_account_id") `)
    await db.query(`CREATE TABLE "block_timestamp" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "timestamp" numeric NOT NULL, CONSTRAINT "PK_e719c30f77b20297166590031f0" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "block_hook" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "type" character varying(4) NOT NULL, "timestamp_id" character varying, CONSTRAINT "PK_d13c0d667b8b8e99976d382a2a8" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_56fc64da61218385f47f523cdc" ON "block_hook" ("timestamp_id") `)
    await db.query(`CREATE TABLE "extrinsic" ("id" character varying NOT NULL, "hash" text NOT NULL, CONSTRAINT "PK_80d7db0e4b1e83e30336bc76755" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "event_a" ("id" character varying NOT NULL, "in_extrinsic" text, "in_block" integer NOT NULL, "network" character varying(10) NOT NULL, "index_in_block" integer NOT NULL, "field1" text NOT NULL, CONSTRAINT "PK_763beab67e26db532ef9ea9ca9c" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "event_b" ("id" character varying NOT NULL, "in_extrinsic" text, "in_block" integer NOT NULL, "network" character varying(10) NOT NULL, "index_in_block" integer NOT NULL, "field2" text NOT NULL, "status_list" jsonb, CONSTRAINT "PK_c697c9a0feedb1087a11f0c2037" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "complex_entity" ("id" character varying NOT NULL, "arg1" text, "arg2" text, CONSTRAINT "PK_ef2629bdec095880f296f009ef0" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "event_c" ("id" character varying NOT NULL, "in_extrinsic" text, "in_block" integer NOT NULL, "network" character varying(10) NOT NULL, "index_in_block" integer NOT NULL, "field3" text NOT NULL, "complex_field_id" character varying NOT NULL, CONSTRAINT "PK_7f827f456a01b66dce6324dd06b" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_2bf352062655c40ae9b14634f3" ON "event_c" ("complex_field_id") `)
    await db.query(`CREATE TABLE "system_event" ("id" character varying NOT NULL, "params" jsonb NOT NULL, "array_field" text array, CONSTRAINT "PK_387d2d01bb48af5099e53bd14cf" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "issue_payment" ("id" character varying NOT NULL, "amount" integer NOT NULL, "issue_id" character varying NOT NULL, CONSTRAINT "REL_1f6fb49d1dd84a72aadace2d16" UNIQUE ("issue_id"), CONSTRAINT "PK_0cc9f8dc537ecf5fa4fbc49ab4d" PRIMARY KEY ("id"))`)
    await db.query(`CREATE UNIQUE INDEX "IDX_1f6fb49d1dd84a72aadace2d16" ON "issue_payment" ("issue_id") `)
    await db.query(`CREATE TABLE "issue_cancellation" ("id" character varying NOT NULL, "block" integer NOT NULL, "issue_id" character varying NOT NULL, CONSTRAINT "REL_7d5b640028a9cd5a6984fe7d9d" UNIQUE ("issue_id"), CONSTRAINT "PK_b10189e5800b6ee824138100f1e" PRIMARY KEY ("id"))`)
    await db.query(`CREATE UNIQUE INDEX "IDX_7d5b640028a9cd5a6984fe7d9d" ON "issue_cancellation" ("issue_id") `)
    await db.query(`CREATE TABLE "issue" ("id" character varying NOT NULL, CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7" PRIMARY KEY ("id"))`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_e2f71240f767a903a4fe85ce25a" FOREIGN KEY ("from_account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_e588c446185bd0c7e4861bb66bb" FOREIGN KEY ("to_account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "block_hook" ADD CONSTRAINT "FK_56fc64da61218385f47f523cdc8" FOREIGN KEY ("timestamp_id") REFERENCES "block_timestamp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "event_c" ADD CONSTRAINT "FK_2bf352062655c40ae9b14634f3c" FOREIGN KEY ("complex_field_id") REFERENCES "complex_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "issue_payment" ADD CONSTRAINT "FK_1f6fb49d1dd84a72aadace2d167" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "issue_cancellation" ADD CONSTRAINT "FK_7d5b640028a9cd5a6984fe7d9d2" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`DROP TABLE "account"`)
    await db.query(`DROP TABLE "transfer"`)
    await db.query(`DROP INDEX "public"."IDX_e2f71240f767a903a4fe85ce25"`)
    await db.query(`DROP INDEX "public"."IDX_e588c446185bd0c7e4861bb66b"`)
    await db.query(`DROP TABLE "block_timestamp"`)
    await db.query(`DROP TABLE "block_hook"`)
    await db.query(`DROP INDEX "public"."IDX_56fc64da61218385f47f523cdc"`)
    await db.query(`DROP TABLE "extrinsic"`)
    await db.query(`DROP TABLE "event_a"`)
    await db.query(`DROP TABLE "event_b"`)
    await db.query(`DROP TABLE "complex_entity"`)
    await db.query(`DROP TABLE "event_c"`)
    await db.query(`DROP INDEX "public"."IDX_2bf352062655c40ae9b14634f3"`)
    await db.query(`DROP TABLE "system_event"`)
    await db.query(`DROP TABLE "issue_payment"`)
    await db.query(`DROP INDEX "public"."IDX_1f6fb49d1dd84a72aadace2d16"`)
    await db.query(`DROP TABLE "issue_cancellation"`)
    await db.query(`DROP INDEX "public"."IDX_7d5b640028a9cd5a6984fe7d9d"`)
    await db.query(`DROP TABLE "issue"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_e2f71240f767a903a4fe85ce25a"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_e588c446185bd0c7e4861bb66bb"`)
    await db.query(`ALTER TABLE "block_hook" DROP CONSTRAINT "FK_56fc64da61218385f47f523cdc8"`)
    await db.query(`ALTER TABLE "event_c" DROP CONSTRAINT "FK_2bf352062655c40ae9b14634f3c"`)
    await db.query(`ALTER TABLE "issue_payment" DROP CONSTRAINT "FK_1f6fb49d1dd84a72aadace2d167"`)
    await db.query(`ALTER TABLE "issue_cancellation" DROP CONSTRAINT "FK_7d5b640028a9cd5a6984fe7d9d2"`)
  }
}
