services:
  postgres:
    image: postgres:12
    ports:
      - "${DB_PORT_PG}:5432"
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: ["postgres", "-c", "log_statement=all"]

  cockroach:
    image: cockroachdb/cockroach:v21.2.9
    ports:
      - "${DB_PORT_COCKROACH}:26257"
    command: [
       "start-single-node",
       "--insecure"
    ]
