services:
  postgres:
    image: postgres:12
    ports:
      - "${DB_PORT_PG}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    command: ["postgres", "-c", "log_statement=all"]

  cockroach:
    image: cockroachdb/cockroach:v23.1.8
    ports:
      - "${DB_PORT_COCKROACH}:26257"
    command: [
      "start-single-node",
      "--insecure"
    ]
