name: Update container image

on:
  push:
    branches:
      - firesquid

env:
  INGEST_NAME: ghcr.io/${{ github.repository_owner }}/substrate-ingest:latest

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build substrate-ingest image
        run: docker build . --target substrate-ingest -t firesquid --tag $PROCESSOR_NAME
        working-directory: squid-blockexplorer

      - name: Push processor image
        run: docker push $PROCESSOR_NAME
