name: github-release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/arrowsquid
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Configure git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - uses: ./.github/actions/publish-releases
