name: test unit
on:
  pull_request:
  workflow_dispatch:

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: run unit tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build project
        run: node common/scripts/install-run-rush.js build

      - name: Run tests
        run: node common/scripts/install-run-rush.js test

  test-lfs:
    name: run LFS test suite
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build project
        run: node common/scripts/install-run-rush.js build

      - name: Run LFS tests
        run: node common/scripts/install-run-rush.js test:lfs
